# <a name="gotop"></a>Table of Contents
[Points to Remember](#points)

[Numpy](#startingnumpy)
   + [Advantages of Numpy](#numpyadvantages)
   + [Creating Array](#array)
   + [Coverting list to array using numpy](#listtoarray)
   + [Array Indexing](#arrayindexing)
   + [Array Slicing](#arrayslicing)
   + [Array Concatenation](#arrayconcatenation)

[Pandas](#pandas)

[Exploring ML Dataset](#exploring)

[Building a ML Model using Random Forest](#building)
+ [Building the model](#buildingthemodel)
+ [Predicting the accuracy](#prediction)
#Introduction to Numpy and Pandas

The pandas library has emerged into a power house of data manipulation tasks in python since it was developed in 2008. With its intuitive syntax and flexible data structure, it's easy to learn and enables faster data computation. The development of numpy and pandas libraries has extended python's multi-purpose nature to solve machine learning problems as well. The acceptance of python language in machine learning has been phenomenal since then.

In this tutorial, we'll learn about using numpy and pandas **libraries for data manipulation** from scratch. Instead of going into theory, we'll take a practical approach. First, we'll understand the syntax and commonly used functions of the respective libraries. Later, we'll work on a real-life data set.

**Note**: This tutorial is best suited for people who know the basics of python. No further knowledge is expected. 

##<a name="points"></a>Points to be Remembered

+ The data manipulation capabilities of pandas are built on top of the numpy library. In a way, numpy is a dependency of the pandas library.

+ Pandas is best at handling tabular data sets comprising different variable types (integer, float, double, etc.). In addition, the pandas library can also be used to perform even the most naive of tasks such as loading data or doing feature engineering on time series data.

+ Numpy is most suitable for performing basic numerical computations such as mean, median, range, etc. Alongside, it also supports the creation of multi-dimensional arrays.

+ Numpy library can also be used to integrate C/C++ and Fortran code.

+ Remember, python is a zero indexing language unlike R where indexing starts at one.

+ The best part of learning pandas and numpy is the strong active community support you'll get from around the world.

##Environment to be used
At present, we can use [Google Colaboratory](https://colab.research.google.com) for trying out what we are learning. Guess what's the advantage,
+ No installation needed
+ Easily accessible online
+ Pre-installed packages

**Note:** If you are about to use a data set that you would like to upload to colab, errors might occur on chrome, try using Firefox if any error occurs.



#<a name="startingnumpy"></a>Starting off with Numpy


**Numpy** is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. The ancestor of NumPy was Numeric. In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications. NumPy is open-source software and has many contributors. 

**<a name="numpyadvantages"></a>Advantages of Numpy**

It contains among other things:

+ a powerful N-dimensional array object
+ sophisticated (broadcasting) functions
+ tools for integrating C/C++ and Fortran code
+ useful linear algebra, Fourier transform, and random number capabilities
+ Size - Numpy data structures take up less space
+ Performance - they have a need for speed and are faster than lists
+ Functionality - SciPy and NumPy have optimized functions such as linear algebra operations built in.

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.




In [1]:
#After opening a new project on Google colab, let's first import Numpy. 

#load the library and check its version, just to make sure we aren't using an older version
import numpy as np
np.__version__
#the output of the above command shows the version version of numpy available on Colab

'1.15.2'

Next, we can create a list of numbers ranging from 0 to 50, to play with.

In [2]:
# we are using the list and range function to create the list of numbers
numbers = list(range(0,51))
print(numbers)

#The above two lines create and prints a list of numbers ranging from 0 to 50

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


Next, we can convert the integers to string. Converting integers to string / this style of handling lists is known as **list comprehension.**
List comprehension offers a versatile way to handle list manipulations tasks easily. We'll learn about them in other examples. Here's an example.  

In [3]:
str_nums = [str(c) for c in numbers]
type_list = [type(item) for item in numbers]
print("String List: ", str_nums[:5], "Type List: ", type_list[:5])

String List:  ['0', '1', '2', '3', '4'] Type List:  [<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]


### <a name="array"></a>Creating Arrays
Numpy arrays are homogeneous in nature, i.e., they comprise one data type (integer, float, double, etc.) unlike lists.
The following examples shows how to create:
+ array with predefined values
+ array with a set sequence
+ array of even space between the given range of values
+ identity matrix

It's pretty much simple. Take a look at the example below: 

In [4]:
# We can create an array of zeroes using numpy directly.
zeros_array = np.zeros(shape=10, dtype='int')
print("Array with all zeros: \n\n", zeros_array, "\n")


# Here we are creating a 3 row x 5 column matrix
ones_array = np.ones(shape=(3,5), dtype=float)
print("Array with all ones: \n\n", ones_array, "\n")


Array with all zeros: 

 [0 0 0 0 0 0 0 0 0 0] 

Array with all ones: 

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 



In [5]:
# creating a matrix with a predefined value
using_full = np.full((3,5),1.23)
print(using_full)

[[1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]
 [1.23 1.23 1.23 1.23 1.23]]


In [6]:

#create an array with a set sequence
using_arrange = np.arange(0, 20, 2)
print(using_arrange)


[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
#create an array of even space between the given range of values
using_linspace = np.linspace(0, 1, 5)
print(using_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
a = np.random.normal(0, 1, (3, 3))
print(a)

[[ 1.47400679 -0.15309966 -0.35980622]
 [ 0.0485463   0.54669951 -0.94154713]
 [-0.6679935   1.45464777  0.02295126]]


In [9]:
#create an identity matrix
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [100]:
#setting a random seed
np.random.seed(0)


x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension


print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


### <a name="listtoarray"></a>Converting lists to array using Numpy

One of the main advantage of Numpy is the fact that, lists can be easily coverted to arrays using numpy. 

In the below code, we can convert the numbers list created to an array using Numpy


In [11]:
numbers = [10, 20, 30, 40, 50, 60]
numbers_array = np.array(numbers)
numbers_array

array([10, 20, 30, 40, 50, 60])

Next, we can move on to Array Indexing

## <a name="arrayindexing"></a>Array Indexing

The important thing to remember is that indexing in python starts at zero.



In [12]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [13]:
#assess value to index zero
x1[0]

4

In [14]:
#assess fifth value
x1[4]

8

In [15]:
#get the last value
x1[-1]

4

In [16]:
#get the second last value
x1[-2]

8

In [17]:
##in a multidimensional array, we need to specify row and column index
x2 = np.array([[3, 7, 5, 5],
      [0, 1, 5, 9],
      [3, 0, 5, 0]])

In [18]:
##1st row and 2nd column value
x2[2,3]

0

In [19]:
#3rd row and last value from the 3rd column
x2[2,-1]

0

In [20]:
#replace value at 0,0 index
x2[0,0] = 12
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

## <a name="arrayslicing"></a>Array Slicing
Now, we'll learn to access multiple or a range of elements from an array. Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects.

As mentioned earlier, items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [21]:
#first lets create an array in the range of 10
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#from start to 4th position
x[:5] ## same as x[0:5] 

array([0, 1, 2, 3, 4])

In [23]:
#from 4th position to end
x[4:]

array([4, 5, 6, 7, 8, 9])

In [24]:
#from 4th to 6th position
x[4:7]

array([4, 5, 6])

In [25]:
#return elements at even place
x[ : : 2]

array([0, 2, 4, 6, 8])

In [26]:
#return elements from first position step by two
x[1::2]

array([1, 3, 5, 7, 9])

In [27]:
#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## <a name="arrayconcatenation"></a>Array Concatenation
Many a time, we are required to combine different arrays. So, instead of typing each of their elements manually, you can use array concatenation to handle such tasks easily, OR 
Often you may have two or more NumPY arrays and want to concatenate/join/merge them into a single array. Python offers multiple options to join/concatenate NumPy arrays.

Common operations include given two 2d-arrays, how can we concatenate them row wise or column wise. NumPy’s concatenate function allows you to concatenate two arrays either by rows or by columns. Let us see a couple of examples of NumPy’s concatenate function.

In [28]:
#let's start by creating 2 simple arrays
#You can concatenate two or more arrays at once.
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [29]:
#You can also use this function to create 2-dimensional arrays.
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [30]:
#Using its axis parameter, you can define row-wise or column-wise matrix
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### Also, we can split the arrays based on pre-defined positions. Let's see how!

In [31]:
#creating an array in the range of 10
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#Now, let's split this array at 3rd and 6th positions
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)
#the output will have 3 arrays, having 3 elements in the first two and 4 elements in the third array

[0 1 2] [3 4 5] [6 7 8 9]


In [33]:
# Let's try another one.
grid = np.arange(16).reshape((4,4))
grid
upper,lower = np.vsplit(grid,[2])
print (upper, lower)

#Just imagine what is happening in this case, before executing the cell!

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


## <a name="arrayconcatenation"></a> Mathematical Fucntions
In addition to the functions we learned above, there are several other mathematical functions available in the numpy library such as sum, divide, multiple, abs, power, mod, sin, cos, tan, log, var, min, mean, max, etc. which you can be used to perform basic arithmetic calculations.

In [34]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Finding the sum of two arrays.
Numpy arrays can be used for finding the sum of the numbers of two arrays in the same position. I.e instead of looping over the length of two arrays and finding the sum, we can add them up as regular numbers.

In [35]:
# Add the two numpy arrays together.
x+x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##### Power of Vectorization
Vectorization is a very powerful concept where the summation of an array can be done parallelly, thereby increasing speed. Let us now compare how this will give us speed improvements compared to a normal list by comparing the time taken to double the elements of a list vs the time taken to double the values of the numpy array.

In [36]:
import time

In [37]:
# Create an list with elements from 0 to 100000
a = [i for i in range(0, 100000)]
# Clock the start time
start_time = time.time()
# Start the loop for the operation
for i in range(0, 100000):
    a[i] = a[i]*2
print("Total time taken = ", time.time()-start_time)

Total time taken =  0.022212743759155273


Now compare the same for a numpy array

In [38]:
# Create a numpy array with elements from 0 to 100000
a = np.arange(0, 100000)
# Clock the start time
start_time = time.time()
# Start the loop for the operation
a = a*2
print("Total time taken = ", time.time()-start_time)

Total time taken =  0.0006070137023925781


As we can see, the improvements in speed is immense. This helps us a lot when we are processing data of a large length.

Apart from the summation and multiplication, we can perform all the standard arthmetic operations in this manner. 

##### Other operations on a numpy array
A numpy array has built in functions for computing mean, median, sum, etc. They can be done as follows.

In [39]:
# New numpy array
np_arr = np.arange(0, 10)

In [40]:
mean = np_arr.mean()
std = np_arr.std()
arr_sum = np_arr.sum()
mean, std, arr_sum

(4.5, 2.8722813232690143, 45)

Let's move on to pandas now. Make sure you following each line below because it'll help you in doing data manipulation using pandas.

# <a name="pandas"></a>Pandas

Pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. It is free software released under the three-clause BSD license. The name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individuals.

**Library features**

+ DataFrame object for data manipulation with integrated indexing.

+ Tools for reading and writing data between in-memory data structures and different file formats.

+ Data alignment and integrated handling of missing data.

+ Reshaping and pivoting of data sets.

+ Label-based slicing, fancy indexing, and subsetting of large data sets.

+ Data structure column insertion and deletion.

+ Group by engine allowing split-apply-combine operations on data sets.

+ Data set merging and joining.

+ Hierarchical axis indexing to work with high-dimensional data in a lower-dimensional data 
structure.
 
+ Time series-functionality: Date range generation and frequency conversion, moving window statistics, moving window linear regressions, date shifting and lagging.

+ Provides data filtration.

The library is highly optimized for performance, with critical code paths written in Cython or C.

In [41]:
# First, we can import Pandas
import pandas as pd

#here, pd is just an alias for the name pandas (short hand)

In [42]:
# Now we can create a data frame - dictionary is used here where keys get converted to column names and values to row values.
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [43]:
#We can do a quick analysis of any data set using:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

Remember, describe() method computes summary statistics of integer / double variables. To get the complete information about the data set, we can use info() function.

In [44]:
#Among other things, it shows the data set has 5 rows and 2 columns with their respective names.
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
Country    5 non-null object
Rank       5 non-null int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [45]:
#Let's create another data frame.
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [46]:
#Let's sort the data frame by ounces - inplace = True will make changes to the data
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

### <a name="sortingpandas"></a>Sorting the data
We can sort the data by not just one column but multiple columns as well.

In [47]:
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

Often, we get data sets with duplicate rows, which is nothing but noise. Therefore, before training the model, we need to make sure we get rid of such inconsistencies in the data set. Let's see how we can remove duplicate rows.

In [48]:
#create another data with duplicated rows
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [49]:
#sort values 
data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [50]:
#remove duplicates - ta da! 
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

Here, we removed duplicates based on matching row values across all columns. Alternatively, we can also remove duplicates based on a particular column. Let's remove duplicate values from the k1 column.

In [51]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

Now, we will learn to categorize rows based on a predefined criteria. It happens a lot while data processing where you need to categorize a variable. For example, say we have got a column with country names and we want to create a new variable 'continent' based on these country names. In such situations, we will require the steps below:

In [52]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

Now, we want to create a new variable which indicates the type of animal which acts as the source of the food. To do that, first we'll create a dictionary to map the food to the animals. Then, we'll use map function to map the dictionary's values to the keys. Let's see how is it done.

In [53]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'

In [54]:
#create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [55]:
#another way of doing it is: convert the food values to the lower case and apply the function
lower = lambda x: x.lower()
data['food'] = data['food'].apply(lower)
data['animal2'] = data.apply(meat_2_animal, axis='columns')
data

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

Another way to create a new variable is by using the assign function. With this tutorial, as you keep discovering the new functions, you'll realize how powerful pandas is.

In [56]:
data.assign(new_variable = data['ounces']*10)

food  ounces  animal animal2  new_variable
0        bacon     4.0     pig     pig          40.0
1  pulled pork     3.0     pig     pig          30.0
2        bacon    12.0     pig     pig         120.0
3     pastrami     6.0     cow     cow          60.0
4  corned beef     7.5     cow     cow          75.0
5        bacon     8.0     pig     pig          80.0
6     pastrami     3.0     cow     cow          30.0
7    honey ham     5.0     pig     pig          50.0
8     nova lox     6.0  salmon  salmon          60.0

In [57]:
#Let's remove the column animal2 from our data frame.

data.drop('animal2',axis='columns',inplace=True)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

We frequently find missing values in our data set. A quick method for imputing missing values is by filling the missing value with any random number. Not just missing values, you may find lots of outliers in your data set, which might require replacing. Let's see how can we replace values.



In [58]:
#Series function from pandas are used to create arrays
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [59]:
#replace -999 with NaN values
data.replace(-999, np.nan,inplace=True)
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [60]:
#We can also replace multiple values at once.
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace([-999,-1000],np.nan,inplace=True)
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

**Now, let's learn how to rename column names and axis (row names).**

In [61]:

data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [62]:
#Using rename function
data.rename(index = {'Ohio':'SanF'}, columns={'one':'one_p','two':'two_p'},inplace=True)
data

one_p  two_p  three  four
SanF          0      1      2     3
Colorado      4      5      6     7
New York      8      9     10    11

In [63]:
#You can also use string functions
data.rename(index = str.upper, columns=str.title,inplace=True)
data

One_P  Two_P  Three  Four
SANF          0      1      2     3
COLORADO      4      5      6     7
NEW YORK      8      9     10    11

In [64]:
#Next, we'll learn to categorize (bin) continuous variables.

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [65]:
# We'll divide the ages into bins such as 18-25, 26-35,36-60 and 60 and above.

#Understand the output - '(' means the value is included in the bin, '[' means the value is excluded
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [66]:
#To include the right bin value, we can do:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [67]:
#pandas library intrinsically assigns an encoding to categorical variables.
cats.codes

#cats.labels can also be used

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [68]:
#Let's check how many observations fall under each bin
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [69]:
#Also, we can pass a unique name to each label.

bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
new_cats = pd.cut(ages, bins,labels=bin_names)

pd.value_counts(new_cats)

Youth         5
MiddleAge     3
YoungAdult    3
Senior        1
dtype: int64

In [70]:
#we can also calculate their cumulative sum
pd.value_counts(new_cats).cumsum()

Youth          5
MiddleAge      8
YoungAdult    11
Senior        12
dtype: int64

Let's proceed and learn about grouping data and creating pivots in pandas. It's an immensely important data analysis method which you'd probably have to use on every data set you work with.

In [71]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

data1     data2 key1 key2
0  1.254414  1.149076    a  one
1  1.419102 -1.193578    a  two
2 -0.743856  1.141042    b  one
3 -2.517437  1.509445    b  two
4 -1.507096  1.067775    a  one

In [72]:
#calculate the mean of data1 column by key1
grouped = df['data1'].groupby(df['key1'])
grouped.mean()


key1
a    0.388807
b   -1.630647
Name: data1, dtype: float64

In [73]:
# Now, let's see how to slice the data frame.
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-04  0.852926  0.018357  0.428304  0.996278
2013-01-05 -0.491150  0.712678  1.113340 -2.153675
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057

In [74]:
#get first n rows from the data frame
df[:3]

A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-03  0.724006  0.359003  1.076121  0.192141

In [75]:
#slice based on date range
df['20130101':'20130104']

A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-04  0.852926  0.018357  0.428304  0.996278

In [76]:
#slicing based on column names
df.loc[:,['A','B']]

A         B
2013-01-01 -0.686589  0.014873
2013-01-02  0.367974 -0.044724
2013-01-03  0.724006  0.359003
2013-01-04  0.852926  0.018357
2013-01-05 -0.491150  0.712678
2013-01-06 -0.416111 -1.070897

In [77]:
#slicing based on both row index labels and column names
df.loc['20130102':'20130103',['A','B']]

A         B
2013-01-02  0.367974 -0.044724
2013-01-03  0.724006  0.359003

In [78]:
#slicing based on index of columns
df.iloc[3] 

#returns 4th row (index is 3rd)

A    0.852926
B    0.018357
C    0.428304
D    0.996278
Name: 2013-01-04 00:00:00, dtype: float64

In [79]:
#returns a specific range of rows
df.iloc[2:4, 0:2]

A         B
2013-01-03  0.724006  0.359003
2013-01-04  0.852926  0.018357

In [80]:
#returns specific rows and columns using lists containing columns or row indexes
df.iloc[[1,5],[0,2]] 

A         C
2013-01-02  0.367974 -0.302375
2013-01-06 -0.416111  0.221139

In [81]:
#Similarly, we can do Boolean indexing based on column values as well. This helps in filtering a data set based on a pre-defined condition.

df[df.A > 1]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [82]:
#we can copy the data set
df2 = df.copy()
df2['E']=['one', 'one','two','three','four','three']
df2

A         B         C         D      E
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224    one
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404    one
2013-01-03  0.724006  0.359003  1.076121  0.192141    two
2013-01-04  0.852926  0.018357  0.428304  0.996278  three
2013-01-05 -0.491150  0.712678  1.113340 -2.153675   four
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057  three

In [83]:
#select rows based on column values
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03  0.724006  0.359003  1.076121  0.192141   two
2013-01-05 -0.491150  0.712678  1.113340 -2.153675  four

In [84]:
#select all rows except those with two and four
df2[~df2['E'].isin(['two','four'])]


A         B         C         D      E
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224    one
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404    one
2013-01-04  0.852926  0.018357  0.428304  0.996278  three
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057  three

In [85]:
#We can also use a query method to select columns based on a criterion. Let's see how!

#list all columns where A is greater than C
df.query('A > C')

A         B         C         D
2013-01-02  0.367974 -0.044724 -0.302375 -2.224404
2013-01-04  0.852926  0.018357  0.428304  0.996278

In [86]:
#using OR condition
df.query('A < B | C > A')

A         B         C         D
2013-01-01 -0.686589  0.014873 -0.375666 -0.038224
2013-01-03  0.724006  0.359003  1.076121  0.192141
2013-01-05 -0.491150  0.712678  1.113340 -2.153675
2013-01-06 -0.416111 -1.070897  0.221139 -1.123057

Pivot tables are extremely useful in analyzing data using a customized tabular format. I think, among other things, Excel is popular because of the pivot table option. It offers a super-quick way to analyze data.

In [87]:
#create a data frame
data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [88]:
#calculate means of each group
data.pivot_table(values='ounces',index='group',aggfunc=np.mean)


ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [89]:
#calculate count by each group
data.pivot_table(values='ounces',index='group',aggfunc='count')

ounces
group        
a           3
b           3
c           3

**Up till now, we've become familiar with the basics of pandas library using toy examples. Now, we'll take up a real-life data set and use our newly gained knowledge to explore it.**

#<a name="exploring"></a>Exploring an ML Dataset


We'll work with the popular adult data set.The data set has been taken from **UCI Machine Learning Repository**. You can download the [data from here](https://s3-ap-southeast-1.amazonaws.com/he-public-data/datafiles19cdaf8.zip). In this data set, the dependent variable is "target." It is a binary classification problem. We need to predict if the salary of a given person is less than or more than 50K.


In [90]:
'''Here, you've to upload the .csv data file from your system after downloading it from the above link.
Open the file and export the files to a position where it can be easily fetched'''



from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

ImportError: No module named 'google'

In [ ]:
!ls

In [ ]:
#importing pandas using read_csv
import pandas as pd
filename = 'train.csv'
train = pd.read_csv(filename)
filename_test = 'test.csv'
test = pd.read_csv(filename_test)

In [ ]:
#train
#un comment the above code to print the data in train.csv

#test
#un comment the above code to print the data in test.csv


In [ ]:
#check data set
train.info()

We see that, the train data has 32561 rows and 15 columns. Out of these 15 columns, 6 have integers classes and the rest have object (or character) classes. Similarly, we can check for test data. An alternative way of quickly checking rows and columns is

In [ ]:
print ("The train data has",train.shape)
print ("The test data has",test.shape)


In [ ]:
#Let have a glimpse of the data set
train.head()

In [ ]:
nans = train.shape[0] - train.dropna().shape[0]
print ("%d rows have missing values in the train data" %nans)

nand = test.shape[0] - test.dropna().shape[0]
print ("%d rows have missing values in the test data" %nand)

**#We should be more curious to know which columns have missing values.
**

In [ ]:

#only 3 columns have missing values
train.isnull().sum()

In [ ]:
#Let's count the number of unique values from character variables.

cat = train.select_dtypes(include=['O'])
cat.apply(pd.Series.nunique)

Since missing values are found in all 3 character variables, let's impute these missing values with their respective modes.

In [ ]:
#Education
train.workclass.value_counts(sort=True)
train.workclass.fillna('Private',inplace=True)


#Occupation
train.occupation.value_counts(sort=True)
train.occupation.fillna('Prof-specialty',inplace=True)


#Native Country
train['native.country'].value_counts(sort=True)
train['native.country'].fillna('United-States',inplace=True)

In [ ]:
# Let's check again if there are any missing values left.

train.isnull().sum()

Now, we'll check the target variable to investigate if this data is imbalanced or not.

In [ ]:


#check proportion of target variable
train.target.value_counts()/train.shape[0]

We see that 75% of the data set belongs to <=50K class. This means that even if we take a rough guess of target prediction as <=50K, we'll get 75% accuracy. Isn't that amazing? Let's create a cross tab of the target variable with education. With this, we'll try to understand the influence of education on the target variable.

In [ ]:
pd.crosstab(train.education, train.target,margins=True)/train.shape[0]

We see that out of 75% people with <=50K salary, 27% people are high school graduates, which is correct as people with lower levels of education are expected to earn less. On the other hand, out of 25% people with >=50K salary, 6% are bachelors and 5% are high-school grads. Now, this pattern seems to be a matter of concern. That's why we'll have to consider more variables before coming to a conclusion.

If you've come this far, you might be curious to get a taste of building your first machine learning model. In the coming week we'll share an exclusive tutorial on machine learning in python. However, let's get a taste of it here.

We'll use the famous and formidable scikit learn library. Scikit learn accepts data in numeric format. Now, we'll have to convert the character variable into numeric. We'll use the labelencoder function.

In label encoding, each unique value of a variable gets assigned a number, i.e., let's say a variable color has four values ['red','green','blue','pink'].

Label encoding this variable will return output as: red = 2 green = 0 blue = 1 pink = 3

In [ ]:
#load sklearn and encode all object type variables
from sklearn import preprocessing

for x in train.columns:
    if train[x].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(train[x].values))
        train[x] = lbl.transform(list(train[x].values))

In [ ]:
#Let's check the changes applied to the data set.

train.head()

In [ ]:
#As we can see, all the variables have been converted to numeric, including the target variable.

#<50K = 0 and >50K = 1
train.target.value_counts()

#<a name="building"></a>Building a Random Forest Model

<a name="buildingthemodel"></a>Let's create a random forest model and check the model's accuracy.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

y = train['target']
del train['target']

X = train
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1,stratify=y)

#train the RF classifier
clf = RandomForestClassifier(n_estimators = 500, max_depth = 6)
clf.fit(X_train,y_train) no

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                max_depth=6, max_features='auto', max_leaf_nodes=None,
                min_impurity_split=1e-07, min_samples_leaf=1,
                min_samples_split=2, min_weight_fraction_leaf=0.0,
                n_estimators=500, n_jobs=1, oob_score=False, random_state=None,
                verbose=0, warm_start=False)

clf.predict(X_test)

**<a name="prediction"></a>Now, let's make prediction on the test set and check the model's accuracy.**


In [ ]:
#make prediction and check model's accuracy
prediction = clf.predict(X_test)
acc =  accuracy_score(np.array(y_test),prediction)
print ('The accuracy of Random Forest is {}'.format(acc))

#if you get a numpy module missing error, then import numpy

Well, we can do tons of things on this data and improve the accuracy. We'll learn about it in future articles. What's next?

In this tutorial, we divided the train data into two halves and made prediction on the test data. As your exercise, you should use this model and make prediction on the test data we loaded initially. You can perform same set of steps we did on the train data to perform the basic necessities on the available data. 

[Go to Top](#gotop)